Name:           ros-indigo-libmongocxx-ros
Version:        0.3.8
Release:        0%{?dist}
Summary:        ROS libmongocxx_ros package

Group:          Development/Libraries
License:        Apache
URL:            https://github.com/mongodb/mongo-cxx-driver
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       openssl-devel
Requires:       ros-indigo-roscpp
BuildRequires:  boost-devel
BuildRequires:  ca-certificates
BuildRequires:  git
BuildRequires:  openssl-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roscpp
BuildRequires:  scons

%description
A wrapper for the libmongocxx for mongodb_store

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed May 02 2018 Marc Hanheide <marc@hanheide.net> - 0.3.8-0
- Autogenerated by Bloom

* Fri Sep 15 2017 Marc Hanheide <marc@hanheide.net> - 0.3.6-1
- Autogenerated by Bloom

