Name:           ros-jade-mongodb-store
Version:        0.1.19
Release:        0%{?dist}
Summary:        ROS mongodb_store package

Group:          Development/Libraries
License:        MIT
URL:            http://www.ros.org/wiki/mongodb_store
Source0:        %{name}-%{version}.tar.gz

Requires:       libmongo-client-devel
Requires:       mongodb
Requires:       mongodb-devel
Requires:       python-pymongo
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-mongo-cxx-driver
Requires:       ros-jade-mongodb-store-msgs
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
Requires:       ros-jade-std-msgs
Requires:       ros-jade-std-srvs
BuildRequires:  libmongo-client-devel
BuildRequires:  mongodb
BuildRequires:  mongodb-devel
BuildRequires:  openssl-devel
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-mongo-cxx-driver
BuildRequires:  ros-jade-mongodb-store-msgs
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rospy
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-std-srvs

%description
A package to support MongoDB-based storage and analysis for data from a ROS
system, eg. saved messages, configurations etc

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Oct 28 2015 Chris Burbridge <cburbridge@gmail.com> - 0.1.19-0
- Autogenerated by Bloom

* Tue Sep 01 2015 Chris Burbridge <cburbridge@gmail.com> - 0.1.17-0
- Autogenerated by Bloom

* Tue Aug 04 2015 Chris Burbridge <cburbridge@gmail.com> - 0.1.16-0
- Autogenerated by Bloom

