Name:           ros-kinetic-mongodb-store
Version:        0.4.2
Release:        0%{?dist}
Summary:        ROS mongodb_store package

Group:          Development/Libraries
License:        MIT
URL:            http://www.ros.org/wiki/mongodb_store
Source0:        %{name}-%{version}.tar.gz

Requires:       mongodb
Requires:       python-pymongo
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-libmongocxx-ros
Requires:       ros-kinetic-mongodb-store-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-std-srvs
Requires:       ros-kinetic-topic-tools
BuildRequires:  mongodb
BuildRequires:  openssl-devel
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-libmongocxx-ros
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-mongodb-store-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-topic-tools

%description
A package to support MongoDB-based storage and analysis for data from a ROS
system, eg. saved messages, configurations etc

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Jun 04 2018 Nick Hawes <nickh@robots.ox.ac.uk> - 0.4.2-0
- Autogenerated by Bloom

* Tue May 29 2018 Nick Hawes <nickh@robots.ox.ac.uk> - 0.4.1-0
- Autogenerated by Bloom

* Wed May 23 2018 Nick Hawes <nickh@robots.ox.ac.uk> - 0.4.0-0
- Autogenerated by Bloom

* Wed May 02 2018 Nick Hawes <nickh@robots.ox.ac.uk> - 0.3.8-0
- Autogenerated by Bloom

* Thu Dec 14 2017 Nick Hawes <nickh@robots.ox.ac.uk> - 0.3.7-0
- Autogenerated by Bloom

* Fri Sep 15 2017 Chris Burbridge <cburbridge@gmail.com> - 0.3.6-0
- Autogenerated by Bloom

